spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apiplatform
    username: postgres
    password: Aditya@2004  # Replace with your actual PostgreSQL password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  secret: your_secret_key_here
  expiration: 86400000

server:
  port: 8080  # Change this from 5432 to 8080 or another free port